version: '3'
services:
  api:
    image: vstu_eds_back:latest
    container_name: vstu_eds_back
    env_file:
      - ./.env
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./trigger:/opt/app/trigger

networks:
  default:
    name: api_network