version: '3'
services:
  api:
    image: vstu_eds_back:latest
    container_name: vstu_eds_back
    environment:
      DB_HOST: mysqldb
    restart: always
    ports:
      - 3000:3000

networks:
  default:
    name: bridge